@backend_HostAddress = http://localhost:5049

POST {{backend_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "username": "ivw53anivan",
  "password": "pise4kaya"
}
###
POST {{backend_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "username": "ivw53anivan",
  "password": "pise4kaya"
}

###
